### ISSUE TITLE
Create How to guide for MBON metadata

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/mbon-docs#15]
Per the MBON DMAC WG meeting on 11/8 - I'd like to start a page for a how to guide for MBON metadata. Starting with the EML OBIS-USA can use.

cc: @albenson-usgs

**Comment by AbbyBenson** [comment]
[EML Metadata Template.docx](https://github.com/ioos/mbon-docs/files/9964435/EML.Metadata.Template.docx)
Here is the template I give people. Maybe we can modify this to include MBON needs/requests/context?

**Comment by MathewBiddle** [comment]
You rock! I'll markdown'ify this into the webpage, if that's alright.

**Comment by MathewBiddle** [comment]
On this page https://ioos.github.io/mbon-docs/metadata.html#metadata or maybe a new page https://ioos.github.io/mbon-docs/metadata.html#metadata-eml

**Comment by MathewBiddle** [comment]
Have a look-see here https://ioos.github.io/mbon-docs/metadata-eml.html

**Comment by AbbyBenson** [comment]
Looks good! Although we lost what is required (e.g. Taxonomic Coverage, Temporal Coverage, etc are not required). I wonder if there is a way to bring that back in? Next we need to come to consensus on what metadata pieces we would need to 1) Identify MBON 2) tag a dataset in the way that was described at the last MBON DMAC meeting.

**Comment by MathewBiddle** [comment]
Are the required ones the ones that are highlighted in your Word Doc?

**Comment by AbbyBenson** [comment]
Yes

**Comment by MathewBiddle** [comment]
Okay, the page should be updated to reflect your comments. https://ioos.github.io/mbon-docs/metadata-eml.html

1. Can we use generic keyword lists, or would it be more efficient to establish MBON as some entity to be referenced in the metadata record (eg. institution, project). I know there are vocabularies for `entities` I just can't find them right now.
2. Once we figure out the answer to 1. we can update this guidance to reflect the process.

I also wonder if we should recommend a way to collect this information (word doc vs writing xml, other options?). We want to be cognizant of the resources available...

**Comment by MathewBiddle** [comment]
Should we discuss this during the Dec 13 MBON DMAC WG meeting?

**Comment by MathewBiddle** [comment]
Discussing during WG meeting today. I'll open new issues as appropriate
