### ISSUE TITLE
Update documentation on sending data to OBIS

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/mbon-docs#28]
There are now issue templates for "thinking about submitting data" and "ready for review" datasets when aligning to Darwin Core and submitting to OBIS-USA. The documentation here should be updated to reference those issue templates:

https://github.com/ioos/bio_data_guide/issues/new/choose

**Comment by MathewBiddle** [comment]
@albenson-usgs @sformel-usgs what do you think about using the bio-data-guide issue templates as a sort of submission system for OBIS-USA?

I would like to remove the bullet `Email Darwin Core aligned files to Abby Benson.` from [here](https://ioos.github.io/mbon-docs/mbon-data-flow.html).

**Comment by AbbyBenson** [comment]
Hey Matt- Steve and I chatted about this today. We are most comfortable having people email although we would suggest changing to "Email Darwin Core aligned files to [OBIS-USA](mailto:obis-usa@usgs.gov)." Our reasons are that it's more future proof (changes in how agencies use or don't use GitHub occurs but email is always used), seems to be how most data providers are most comfortable sending their data, and is the most manageable option for us. We are ok though if for this particular community (MBON) you would rather point them to the bio-data-guide templates instead. We just are not going to make the switch for all data providers and will still have email as the primary option for all other communities.

**Comment by MathewBiddle** [comment]
Thanks for this explanation. This makes sense and I'm glad to know there is a more generalized email we can put out there. 

For the MBON project documentation on this site, I will update the text to state:
* Email Darwin Core aligned files to [OBIS-USA](mailto:obis-usa@usgs.gov).
* Or, use the [Dataset Review Request issue](https://github.com/ioos/bio_data_guide/issues/new?assignees=albenson-usgs%2C7yl4r&labels=data+help&template=dataset_review.yaml&title=%5Bdataset%5D%3A+).
