### ISSUE TITLE
create flowchart for MBON data flow +data.ioos.gov +data.gov etc

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/mbon-docs#40]
update https://github.com/ioos/mbon-docs/blob/gh-pages/_docs/images/MBON_Data_Flow.png

using mermaid to show how records get to data.ioos.us, noaa one stop, data.gov.

**Comment by MathewBiddle** [comment]
https://mermaid.js.org/syntax/flowchart.html

**Comment by MathewBiddle** [comment]
Testing
```mermaid

%%{
  init: {
    'theme': 'base',
    'themeVariables': {
      'primaryColor': '#007396',
      'primaryTextColor': '#fff',
      'primaryBorderColor': '#003087',
      'lineColor': '#003087',
      'secondaryColor': '#007396',
      'tertiaryColor': '#CCD1D1'
    },
   'flowchart': { 'curve': 'basis' }
  }
}%%

flowchart TD

A["Tabular Data 
& 
Metadata"] 

B[("Raw Data 
Access Point
(eg. RA ERDDAP)")]

C{{"Darwin Core
Alignment"}}

D([NCEI])

E[("IPT
OBIS-USA")]

F[/"MBON 
Data Portal"\]

G([OBIS])

H([GBIF])

I[("IOOS Data Catalog
(data.ioos.us)")]

J[(NOAA OneStop)]

K[(data.gov)]

L[("Commerce
Data Hub")]

M[/"IOC-UNESCO Harmful Algae Information System"\]

N[/"Infographics"\]

A --> B
B --> C
B --> D
C --> E
E --> D
G .-> F
E --> G
E --> H
B -- If using IOOS RA ERDDAP --> I
I --> J
J --> K
K --> L
B .-> F
G .-> M
G .-> N
D .-> N
B .-> N
D .-> F


subgraph products
M
N
F
end

click D "https://www.ncei.noaa.gov" "NCEI" _blank
click F "https://mbon.ioos.us" "MBON" _blank
click G "https://obis.org" "OBIS" _blank
click H "https://gbif.org" "GBIF" _blank
click I "https://data.ioos.us" "IOOS Catalog" _blank
click J "https://data.noaa.gov/onestop/" "NOAA OneStop" _blank
click K "https://data.gov" "data.gov" _blank
```

**Comment by MathewBiddle** [comment]
@mwengren Can you confirm the above diagram w.r.t. data shared via IOOS RA ERDDAP through to commerce data hub?

**Comment by mwengren** [comment]
It's a little (a lot?) more complicated for the OneStop, Data.gov, and Commerce Data Hub data flows.  It's also kind of a moving target, so might not be worth making 100% accurate for now.  

Probably, what's important for IOOS' perspective, is that once metadata makes it to the IOOS Catalog, for the most part it goes on to the other services by some route.  There are some exceptions due to OneStop validation criteria that will exclude some records considered 'valid' by IOOS Catalog. 

Here's an internal presentation from Ken Casey to our NOAA Catalog WG from last year.  It covers all the gory details starting on the slide linked below...

https://docs.google.com/presentation/d/1yksTNbO7Nl704utw6pu-O4Z6RjF-v06XiVqvXfUhW0w/edit#slide=id.g12fe5d64108_0_250

**Comment by MathewBiddle** [comment]
I see. Yeah, I wanted to keep the nuance of the flow to OneStop, Data.gov, and Commerce Data Hub out of this diagram. The hope is to convey the importance of the RA's serving the raw biological observations via their ERDDAP's as that is how these data get into the federal catalogs.

Instead of having the linear flow from IOOS Catalog to OneStop, Data.gov, and Commerce Data Hub I will connect all those nodes directly to IOOS Catalog.

```mermaid

%%{
  init: {
    'theme': 'base',
    'themeVariables': {
      'primaryColor': '#007396',
      'primaryTextColor': '#fff',
      'primaryBorderColor': '#003087',
      'lineColor': '#003087',
      'secondaryColor': '#007396',
      'tertiaryColor': '#CCD1D1'
    },
   'flowchart': { 'curve': 'basis' }
  }
}%%

flowchart TD

A["Tabular Data 
& 
Metadata"] 

B[("Raw Data 
Access Point
(eg. RA ERDDAP)")]

C{{"Darwin Core
Alignment"}}

D([NCEI])

E[("IPT
OBIS-USA")]

F[/"MBON 
Data Portal"\]

G([OBIS])

H([GBIF])

I[("IOOS Data Catalog
(data.ioos.us)")]

J[(NOAA OneStop)]

K[(data.gov)]

L[("Commerce
Data Hub")]

M[/"IOC-UNESCO Harmful Algae Information System"\]

N[/"Infographics"\]

A --> B
B --> C
B --> D
C --> E
E --> D
G .-> F
E --> G
E --> H
B -- If using IOOS RA ERDDAP --> I
I --> J
I --> K
I --> L
D --> J
D --> K
D --> L
B .-> F
G .-> M
G .-> N
D .-> N
B .-> N
D .-> F


subgraph Example Products
M
N
F
end

subgraph Federal Catalogs
J
K
L
end

click D "https://www.ncei.noaa.gov" "NCEI" _blank
click F "https://mbon.ioos.us" "MBON" _blank
click G "https://obis.org" "OBIS" _blank
click H "https://gbif.org" "GBIF" _blank
click I "https://data.ioos.us" "IOOS Catalog" _blank
click J "https://data.noaa.gov/onestop/" "NOAA OneStop" _blank
click K "https://data.gov" "data.gov" _blank
```

**Comment by MathewBiddle** [comment]
I like the mermaid diagrams, but I don't like that the copy button copies the diagram code not the chart as an image. I wonder if there is a mermaid configuration to make that option available. 

Right now, I paste the diagram code into https://mermaid.live/edit and use the "COPY IMAGE TO CLIPBOARD" feature there...

**Comment by ocefpaf** [comment]
> I like the mermaid diagrams, but I don't like that the copy button copies the diagram code not the chart as an image. I wonder if there is a mermaid configuration to make that option available.

I don't think so b/c the figure is vector graphics and one would need to rasterize (export) it first. The only too I found to do that is  mermaid's own cli: https://gist.github.com/fkurz/3a7380c155bdabb9c47707d4989da9e0

**Comment by ocefpaf** [comment]
Annnd of course there is a better way. Copy-n-paste the diagram on VSCode and use this extension: https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.mermaid-export (or this online too https://mermaid-js.github.io/docs/mermaid-live-editor-beta)

**Comment by MathewBiddle** [comment]
Let's add this diagram to the jekyll docs https://jackgruber.github.io/2021-05-09-Embed-Mermaid-in-Jekyll-without-plugin/

**Comment by MathewBiddle** [comment]
Cleaning up the diagram for federal catalogs and example products

```mermaid

%%{
  init: {
    'theme': 'base',
    'themeVariables': {
      'primaryColor': '#007396',
      'primaryTextColor': '#fff',
      'primaryBorderColor': '#003087',
      'lineColor': '#003087',
      'secondaryColor': '#007396',
      'tertiaryColor': '#CCD1D1'
    },
   'flowchart': { 'curve': 'basis' }
  }
}%%

flowchart TD

A["Tabular Data 
& 
Metadata"] 

B[("Raw Data 
Access Point
(eg. RA ERDDAP)")]

C{{"Darwin Core
Alignment"}}

D[(NCEI)]

E[("IPT
OBIS-USA")]

F[/"MBON 
Data Portal"\]

G([OBIS])

H([GBIF])

I[("IOOS Data Catalog
(data.ioos.us)")]

J[(NOAA OneStop)]

K[(data.gov)]

L[("Commerce
Data Hub")]

M[/"IOC-UNESCO Harmful Algae Information System"\]

N[/"Infographics"\]

A --> B
B --> C
E --> D
B --> D
C --> E
E --> G
E --> H
B -- If using IOOS RA ERDDAP --> I

D --> FC
I --> FC

H .-> EP
G .-> EP
B .-> EP
D .-> EP


subgraph EP [Example Products]
M
N
F
end

subgraph FC [Federal Catalogs]
J
K
L
end

click D "https://www.ncei.noaa.gov" "NCEI" _blank
click F "https://mbon.ioos.us" "MBON" _blank
click G "https://obis.org" "OBIS" _blank
click H "https://gbif.org" "GBIF" _blank
click I "https://data.ioos.us" "IOOS Catalog" _blank
click J "https://data.noaa.gov/onestop/" "NOAA OneStop" _blank
click K "https://data.gov" "data.gov" _blank
```

**Comment by MathewBiddle** [comment]
@laurabrenskelle we should be able to add this now

https://github.com/ioos/documentation-theme-jekyll/issues/15

**Comment by MathewBiddle** [comment]
I think the process is to replace these lines
https://github.com/ioos/mbon-docs/blob/5fc77410c35335949daaea54e4508826fdfa130e/_docs/mbon-data-flow.md?plain=1#L10-L13

with 
```
{% raw %}
<div class="mermaid">
DIAGRAM HERE
</div>
{% endraw %}
```

Where DIAGRAME HERE is replaced with the mermaid diagram source code in https://github.com/ioos/mbon-docs/issues/40#issuecomment-1845620380 (click `Edit` to see it)

**Comment by MathewBiddle** [comment]
Diagram is available at https://ioos.github.io/mbon-docs/mbon-data-flow.html
