### ISSUE TITLE
Show the value of standardizing and sharing to OBIS

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/mbon-docs#42]
Statement: There have been some conversations about how US MBON can build an integrated product with all the data being collected. 

Requirements: IMO, product should be built on data that have been standardized and shared to OBIS.

Problem: What should an integrated product be? The minimum data shared with OBIS are occurrences of a species at a location and time. Can we do something with that? Are there additional standardized data available we can integrate to make something?

My thoughts: 
* Out of all the datasets mobilized to OBIS from MBON projects (https://obis.org/institute/23070), I wonder how much and what type of **additional** data are available? 
* Once we know that, can we make a useful product from the occurrences and those additional measures?
* Finally, from this exercise, develop guidance to other projects on what additional data to standardize in DwC and share? 

I think this notebook will help as a start:
* https://ioos.github.io/ioos_code_lab/content/code_gallery/data_access_notebooks/2022-11-23_pyobis_example.html

**Comment by laurabrenskelle** [comment]
Another topic I would also like to tackle.

**Comment by MathewBiddle** [comment]
Somewhat tangentially related to this, but showing the value nonetheless. Mind tagging up with @sformel-usgs and seeing what he did to collect statistics about OBIS/GBIF downloads and citations?

Here's my notebook where I started playing around with OBIS/GBIF download statistics https://github.com/MathewBiddle/sandbox/blob/main/notebooks/MBON_OBIS_statistics.ipynb

**Comment by sformel-usgs** [comment]
I can help with this. Mostly just commenting so I'll get notifications.

**Comment by MathewBiddle** [comment]
This is done. See https://github.com/ioos/ioos_metrics/blob/main/notebooks/mbon_citation_visualizations.ipynb
